version: "3"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: SECRET
      POSTGRES_PASSWORD: SECRET
    volumes:
      - pgdata:/var/lib/postgresql/data

  speak:
    image: speak1.0:latest
    ports:
      - "443:443"
    depends_on: [postgres]

volumes:
  pgdata:
    external: true